### PR TITLE
Add image

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by timkurvers** [comment]
Hah nice! We should probably keep some of the documentation though?

Will that link remain working after we delete the branch?

**Comment by 3lvis** [comment]
@timkurvers the link would have to be updated, the documentation shouldn't be needed since it's a copy paste nothing that we wrote.

**Comment by timkurvers** [comment]
It contains usage instructions on how to run the bot locally for example. That is useful regardless of author.

**Comment by 3lvis** [comment]
> It contains usage instructions on how to run the bot locally for example. That is useful regardless of author.

A link to the main page should be enough, that information is there.

**Comment by timkurvers** [comment]
Which main page are you thinking about?

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/bot/blob/add-cover/README.md

**Comment by timkurvers** [comment]
Looks great. Maybe right-aligning the bot would be nice, and have it wrap around the text?

**Comment by 3lvis** [comment]
Maybe in a next PR :)

**Pull request merged**
