### PR TITLE
Add hubot-darts

### PR DESCRIPTION
**Pull request by espenhogbakk**
Adds hubot-darts package to Hyperbot.

https://github.com/hubot-scripts/hubot-darts

### CODE REVIEW

**Comment by timkurvers** [comment]
Sweet! Could we order the dependencies? `npm install hubot-darts --save` will do this automatically.

**Comment by espenhogbakk** [comment]
Of cuuurse

**Comment by espenhogbakk** [comment]
Doh, know its in there twice

**Comment by timkurvers** [comment]
Teehee! :smile:

**Comment by timkurvers** [comment]
Is it supposed to be `hubots-darts` in external-scripts or not? Documentation is a bit vague! :open_mouth:

**Comment by espenhogbakk** [comment]
> Add the package hubot-darts entry to the external-scripts.json file (you may need to create this file).
> 
> To enable the script, add the hubot-darts entry to the packages.json file (you may need to create this file).

I think he has mixed them up in the documentation though.

**Pull request merged**
